### PR TITLE
Removed remote notifications.

### LINKED ISSUE #16: Check if notifications are necessary
Verify if remote notification are really necessary to let the app work even when is closed.

### PR DESCRIPTION
**Pull request by matteoKuama**
The plugin behaviour isn't affected by that.
I added Console logs that will print details under the Category "kuama".

### CODE REVIEW

**Review by GabM3 — DISMISSED** [review]

**Comment by kuamanet** [comment]
@matteoKuama from the [docs](https://developer.apple.com/documentation/corelocation/cllocationmanager/1423531-startmonitoringsignificantlocati)
> Apps can expect a notification as soon as the device moves 500 meters or more from its previous notification. It should not expect notifications more frequently than once every five minutes. If the device is able to retrieve data from the network, the location manager is much more likely to deliver notifications in a timely manner.

Does this affect the features of My First Alert?

**Comment by matteoKuama** [comment]
Changed the location retrieving mechanism:
- every time we have a new location it draws an area around us of approx 100mts.
- when the app is terminated, if the user exits from it the app launches again the location updates that will go on forever 
- to stop it nothing has changed: the stopUpdates method must be called

**Comment by matteoKuama** [comment]
Change region monitoring to region state monitoring.
When the app is launched it will check forever if the user is inside a region around himself.
Doing so it will update the location, publish it to the stream and recall himself forever.
To stop it, just call stopUpdates that will stop monitoring regions as well.

**Comment by kuamanet** [comment]
@matteoKuama  While we are at this, do we want to introduce some delay between the region checks to avoid battery drainig?

**Comment by matteoKuama** [comment]
Added an update delay for monitoring regions.
If it is not set, the default value is 10 seconds.

While setting his value note that:
- it must be a Double representing the seconds;
- if passing a negative number it will throw an error;
- the delay is valid only for monitoring regions;

**Review by kuamanet — APPROVED** [review]

**Pull request merged**
